### ISSUE TITLE
`lucky init` fails when directory already exists

### ISSUE THREAD

**Issue by ianagne** [luckyframework/cli#47]
## Steps to repeat:
1) create a new directory (e.g. `lucky_charms/` )
2) run `lucky init lucky_charms`

## Error output:
```
file or directory lucky_charms already exists
Adding deps to shards.yml
Error opening file 'shard.yml' with mode 'r': No such file or directory (Errno)
0x104d4be80: *raise<Errno>:NoReturn at ??
0x104d58b34: *File::new<String, String, Int32, Nil, Nil>:File at ??
0x104d74def: *LuckyCli::Generators::Web@LuckyCli::GeneratorHelpers#append_text<String, String>:Nil a0x104d74def: *LuckyCli::Generators::Web@LuckyCli::GeneratorHelpers#append_text<String, String>:Nil at ??
Unhandled exception in spawn:
End of file reached (IO::EOFError)
0x104d5a480: *raise<IO::EOFError>:NoReturn at ??
0x104d699d4: ~procProc(Nil)@/usr/local/Cellar/crystal-lang/0.23.1_3/src/event/signal_handler.cr:93 at ??
0x104d71af6: *LuckyCli::Generators::Web#run:Nil at ??
0x104d49f65: __crystal_main at ??
0x104d6a7f5: main at ??
```
## Desired behavior

I expected the project to initialize since the directory was empty.  Thoughts?  I'd love to help out with this.

**Comment by paulcsmith** [comment]
@ianagne Good catch! I think it should not initialize if the project is empty, but should raise a prettier error like

```
There is already a directory called {project_name}. Please delete it and try again, or name your project something different.
```

In the future we could ask "this directory is empty, would you like to initialize the project in it?", but for now I think it's best to keep things simple.

If you (or someone else) wants to take a crack at it, that'd be great. You would probably want to start here: https://github.com/luckyframework/cli/blob/master/src/generators/web.cr

That class generates a new lucky web project. In the `#run` method you would probably start off with a check like `ensure_directory_does_not_exist` or something along those lines.

**Comment by coderhs** [comment]
@paulcsmith I would like to have go with this issue. 😄 👍

**Comment by paulcsmith** [comment]
@coderhs That'd be great! Thank you

**Comment by coderhs** [comment]
I just noticed an interesting point. let me know if we want to handle that.

If the folder that exist is a crystal project, then it won't fail but add our code to that project. 

```
crystal init app lucky_charms
lucky init lucky_charms
```

My PR would also avoid such a cases as well.

**Comment by paulcsmith** [comment]
Hmm I'm not sure so I think for now let's go with the warning that they need to use a different name or remove the folder. That's for sure better than throwing an error! Then we can figure out how to make it a bit nicer in the future. Does that sound good?

**Comment by coderhs** [comment]
ya. btw: this is error message `"Folder with project name exists, kindly give a new name."`. Let me know if that is fine, I am writing the test for the method, will send the PR.

**Comment by paulcsmith** [comment]
How about? "Folder with #{project_name} already exists, please use a different name" And thanks so much for working on this
